dogs/urls.py
from django.conf.urls import patterns, include, url
from views import *

urlpatterns = patterns('',
	url(r'^$', our_dogs, name='our_dogs'),
	url(r'^males/$', males, name='males'),
	url(r'^females/$', females, name='females'),
	url(r'^(?P<dog_id>\d+)/$', dog_page, name='dog_page')

)

gallery/urls.py
from django.conf.urls import url, patterns
from views import albums, album

urlpatterns = patterns('',
	url(r'^albums/$', albums, name='albums'),
	url(r'^(?P<album_id>\d+)/(?P<view>full|thumbnails)/$', album, name='album'),

)

kennel/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()



from django.conf.urls import *
from django.conf import settings

from views import home
from contacts.views import ContactCreateView
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'kennel.views.home', name='home'),
    # url(r'^kennel/', include('kennel.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', home, name='home'),
    #url(r'^gallery/', include('photogallery.urls', namespace='photogallery')),
    url(r'^news/', include('news.urls', namespace='news')),
    url(r'^dogs/', include('dogs.urls', namespace='dogs')),
    url(r'^puppies/', include('puppies.urls', namespace='puppies')),
    url(r'^offsprings/', include('offsprings.urls', namespace='offsprings')),
    url(r'^history/$', TemplateView.as_view(template_name='history.html'), name='history'),
    url(r'^standard/$', TemplateView.as_view(template_name='standard.html'), name='standard'),
    url(r'^whythisbreed/$', TemplateView.as_view(template_name='whythisbreed.html'), name='whythisbreed'),
    url(r'^contacts/$', ContactCreateView.as_view(), name='contacts'),
    url(r'^thanks/$', TemplateView.as_view(template_name='success_contact.html')),
    url(r'^gallery/', include('gallery.urls', namespace='gallery')),
    #url(r'^i18n/', include('django.conf.urls.i18n')),
)


urlpatterns += patterns('',
    
    #(r'^localeurl/', include('localeurl.urls')),\
    (r'^i18n/', include('django.conf.urls.i18n')),
    
)
#for media
urlpatterns += patterns('',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
)

#for captcha 
urlpatterns += patterns('',
    url(r'^captcha/', include('captcha.urls')),
)

dogs/models.py
from django.db import models
import datetime

from gallery.models import Album

class Gender(models.Model):
	gender = models.CharField(max_length=15)

	def __unicode__(self):
		return self.gender

class Dog(models.Model):
	name = models.CharField(max_length=80, blank=True)
	mother = models.CharField(max_length=80, blank=True)
	father = models.CharField(max_length=80, blank=True)
	breeder = models.CharField(max_length=80, blank=True)
	photo = models.ImageField(upload_to='media', blank=True)
	sex = models.ForeignKey(Gender)
	birthday = models.DateField()
	pedigree = models.URLField(max_length=150, blank=True)
	hd = models.CharField(max_length = 40, blank=True) 
	mdr1 = models.CharField(max_length = 40, blank=True)
	dm = models.CharField(max_length=40, blank=True)
	titles = models.TextField(max_length=400, blank=True)
	training = models.CharField(max_length=80, blank=True)
	about_dog = models.TextField(max_length=400, blank=True)
	gallery = models.ForeignKey(Album, blank=True, null=True)

	def __unicode__(self):
		return self.name

kennel/dogs/models.py
from django.db import models
import datetime

from gallery.models import Album

class Gender(models.Model):
	gender = models.CharField(max_length=15)

	def __unicode__(self):
		return self.gender

class Dog(models.Model):
	name = models.CharField(max_length=80, blank=True)
	breeder = models.CharField(max_length=80, blank=True)
	photo = models.ImageField(upload_to='media', blank=True)
	sex = models.ForeignKey(Gender)
	birthday = models.DateField()
	pedigree = models.URLField(max_length=150, blank=True)
	hd = models.CharField(max_length = 40, blank=True) 
	mdr1 = models.CharField(max_length = 40, blank=True)
	dm = models.CharField(max_length=40, blank=True)
	titles = models.TextField(max_length=400, blank=True)
	training = models.CharField(max_length=80, blank=True)
	about_dog = models.TextField(max_length=400, blank=True)
	gallery = models.ForeignKey(Album)

	def __unicode__(self):
		return self.name

dogs/views.py
from django.shortcuts import render
from models import Gender, Dog

def our_dogs(request):

	#males = Dog.objects.get(Dog.sex.gender = 'Male')
	#females = Dog.objects.get(Dog.sex.gender = 'Female')
	return render(request, 'dogs/our_dogs.html')

def males(request):
	gender = Gender.objects.get(gender_en="Male")
	males = gender.dog_set.all()
	return render(request, 'dogs/males.html', {'males': males})

def females(request):
	gender = Gender.objects.get(gender_en="Female")
	females = gender.dog_set.all()
	return render(request, 'dogs/females.html', {'females': females})

def dog_page(request, dog_id):
	dog = Dog.objects.get(id=dog_id)
	print dog.photo
	return render(request, 'dogs/dog_page.html', {'dog': dog})

dogs/templates/dogs/dog_page.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{{ dog.name }}{% endblock %}
{% load thumbnail %}
{% block content %}

	<center>
	<h3>{{ dog.name }}</h3>
	{% if dog.mother %} 
	<b>{% trans 'Mother' %}:</b> {{ dog.mother }} x <b>{% trans 'Father' %}:</b> {{ dog.father }}
	{% endif %} <br/>
	{% if dog.breeder %}
	<p><b>{% trans 'Breeder' %}:</b> {{ dog.breeder }}</p>
	{% endif %}

	{% if dog.photo %}
		<p><img src="{{ MEDIA_URL}}{{ dog.photo }}" width=500 heigth=500/></p>
	{% else %}
		<img src="{{MEDIA_URL}}media/siluet_sobaki.jpg" wodth=200 height=200/>
	{% endif %}
	</center>

	{% if dog.sex %}
	<p><b>{% trans 'Sex' %}:</b> {{ dog.sex }} </p>
	{% endif %}

	{% if dog.birthday %}
	<p><b>{% trans 'Birthday' %}:</b> {{ dog.birthday }} </p>
	{% endif %}

	{% if dog.pedigree %}
	<p><a href={{ dog.pedigree }}>{% trans 'Pedigree' %} </a></p>
	{% endif %}
	{% if dog.hd or dog.mdr1 or dog.dm %}
	<p><b>{% trans 'Health' %}</b>
	{% endif %}
	{% if dog.hd %}
	ED/HD: {{ dog.hd }},
	{% endif %}

	{% if dog.mdr1 %}
	MDR1 {{ dog.mdr1 }},
	{% endif %}

	{% if dog.dm %}
	DM {{ dog.dm }}</p>
	{% endif %}

	{% if dog.titles %}
	<p><b>{% trans 'Entitlements' %}:</b> {{ dog.titles }}</p>
	{% endif %}

	{% if dog.training %}
	<p><b>{% trans 'Achievements' %}:</b> {{ dog.training }}</p>
	{% endif %}

	{% if dog.about_dog %}
	<p><b>{% trans 'About dog' %}:</b> {{ dog.about_dog }}</p>
	{% endif %}

	{% if dog.gallery.id %}
	<h3><a href="{% url 'gallery:album' dog.gallery.id 'thumbnails' %}">{{ dog.gallery.title }} </a> ({{ dog.gallery.image_set.count }} {% blocktrans count dog.gallery.image_set.count as counter %}image{% plural %}images{% endblocktrans %})</h3>
		<ul>
		{% for img in dog.gallery.image_set.all %}
			{% thumbnail img '200x200' crop='center' as im %}
			<a href="{{ MEDIA_URL }}{{ img }}" rel="prettyPhoto[pp_gal]"><img src='{{ im.url }}' alt="{{ im.title }}" width="{{ im.width }}" height="{{ im.height }}" class='img-rounded'></a>
			{% endthumbnail %}
		{% endfor %}
		</ul>
	{% endif %}

{% endblock %}

dogs/templates/dogs/females.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans 'Our females' %}{% endblock %}

{% block content %}

{% for female in females %}
	<center><h3><a href="{% url 'dogs:dog_page' female.id %}">{{ female.name }}</a></h3>
	{% if female.mother %}
	<b>{% trans 'Mother' %}:</b> {{ female.mother }} x <b>{% trans 'Father' %}:</b> {{ female.father }}
	{% endif %}<br/>
	{% if female.photo %}
		<img src="{{ MEDIA_URL}}{{ female.photo }}" width=500 heigth=500/>
	{% else %}
		<img src="{{MEDIA_URL}}media/siluet_sobaki.jpg" width=400 height=400/>
	{% endif %}
	<p><b>{% trans 'Birthday' %}:</b> {{ female.birthday }}</p>
	</center>
	<div class='row-fluid'>
		<div class='offset8'><a href="{% url 'dogs:dog_page' female.id %}">{% trans 'More' %}...</a></div>
	</div>
{% endfor %}
{% endblock %}

dogs/templates/dogs/males.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans 'Our males' %}{% endblock %}

{% block content %}
{% for male in males %}
	<center>
	<h3><a href="{% url 'dogs:dog_page' male.id %}">{{ male.name }}</a></h3>
	{% if male.mother %}
	<b>{% trans 'Mother' %}:</b> {{ male.mother }} x <b>{% trans 'father' %}:</b> {{ male.father }}
	{% endif %}<br/>
	{% if male.photo %}
		<img src="{{ MEDIA_URL}}{{ male.photo }}" width=500 heigth=500/>
	{% else %}
		<img src="{{MEDIA_URL}}media/siluet_sobaki.jpg" width=400 height=400/>
	{% endif %}
	<p><b>{% trans 'Birthday' %}:</b> {{ male.birthday }}</p>
	</center>
	<div class='row-fluid'>
		<div class='offset8'><a href="{% url 'dogs:dog_page' male.id %}">{% trans 'More' %}...</a></div>
	</div>
{% endfor %}
{% endblock %}

dogs/templates/dogs/our_dogs.html
{% extends 'base.html' %}

{% block title %}Our dogs{% endblock %}

{% block content %}<p>
<a href="{% url 'dogs:males' %}">Males</a>
<a href="{% url 'dogs:females' %}">Females</a></p>
{% endblock %}