dogs/urls.py
from django.conf.urls import patterns, include, url
from views import *

urlpatterns = patterns('',
	url(r'^$', our_dogs, name='our_dogs'),
	url(r'^males/$', males, name='males'),
	url(r'^females/$', females, name='females'),
	url(r'^(?P<dog_id>\d+)/$', dog_page, name='dog_page')

)

gallery/urls.py
from django.conf.urls import url, patterns
from views import albums, album

urlpatterns = patterns('',
	url(r'^albums/$', albums, name='albums'),
	url(r'^(?P<album_id>\d+)/(?P<view>full|thumbnails)/$', album, name='album'),

)

kennel/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()



from django.conf.urls import *
from django.conf import settings

from views import home
from contacts.views import ContactCreateView
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'kennel.views.home', name='home'),
    # url(r'^kennel/', include('kennel.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', home, name='home'),
    #url(r'^gallery/', include('photogallery.urls', namespace='photogallery')),
    url(r'^news/', include('news.urls', namespace='news')),
    url(r'^dogs/', include('dogs.urls', namespace='dogs')),
    url(r'^puppies/', include('puppies.urls', namespace='puppies')),
    url(r'^offsprings/', include('offsprings.urls', namespace='offsprings')),
    url(r'^history/$', TemplateView.as_view(template_name='history.html'), name='history'),
    url(r'^standard/$', TemplateView.as_view(template_name='standard.html'), name='standard'),
    url(r'^whythisbreed/$', TemplateView.as_view(template_name='whythisbreed.html'), name='whythisbreed'),
    url(r'^contacts/$', ContactCreateView.as_view(), name='contacts'),
    url(r'^thanks/$', TemplateView.as_view(template_name='success_contact.html')),
    url(r'^gallery/', include('gallery.urls', namespace='gallery')),
    #url(r'^i18n/', include('django.conf.urls.i18n')),
)


urlpatterns += patterns('',
    
    #(r'^localeurl/', include('localeurl.urls')),\
    (r'^i18n/', include('django.conf.urls.i18n')),
    
)
#for media
urlpatterns += patterns('',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
)

#for captcha 
urlpatterns += patterns('',
    url(r'^captcha/', include('captcha.urls')),
)

puppies/urls.py
from django.conf.urls import patterns, url
from views import puppies, litter

urlpatterns = patterns('',
	url(r'^$', puppies, name='our_puppies'),
	url(r'^(?P<puppies_id>\d+)/$', litter, name='litter'),
)

kennel/puppies/models.py
from django.db import models

import datetime

from gallery.models import Album

class Puppies(models.Model):
	litter = models.CharField(max_length=15)
	mother = models.CharField(max_length=100)
	mother_photo = models.ImageField(upload_to='media', blank=True)
	mother_pedigree = models.URLField(max_length=100, blank=True)
	mother_health = models.CharField(max_length=100, blank=True)
	father = models.CharField(max_length=100)
	father_photo = models.ImageField(upload_to='media', blank=True)
	father_pedigree = models.URLField(max_length=100, blank=True)
	father_health = models.CharField(max_length=100, blank=True)
	birthday = models.CharField(max_length=80, blank=True)
	amount = models.CharField(max_length=40, blank=True)
	gallery = models.ForeignKey(Album)

	class Meta():
		verbose_name_plural = 'Puppies'

	def __unicode__(self):
		return self.litter

puppies/models.py
from django.db import models

import datetime

from gallery.models import Album

class Puppies(models.Model):
	litter = models.CharField(max_length=15)
	mother = models.CharField(max_length=100)
	mother_photo = models.ImageField(upload_to='media', blank=True)
	mother_pedigree = models.URLField(max_length=100, blank=True)
	mother_health = models.CharField(max_length=200, blank=True)
	mother_titles = models.CharField(max_length=100, blank=True)
	mother_training = models.CharField(max_length=100, blank=True)
	father = models.CharField(max_length=100)
	father_photo = models.ImageField(upload_to='media', blank=True)
	father_pedigree = models.URLField(max_length=100, blank=True)
	father_health = models.CharField(max_length=100, blank=True)
	father_titles = models.CharField(max_length=200, blank=True)
	father_training = models.CharField(max_length=100, blank=True)
	birthday = models.DateField(blank=True)
	amount = models.CharField(max_length=40, blank=True)
	gallery = models.ForeignKey(Album, blank=True, null=True)

	class Meta():
		verbose_name_plural = 'Puppies'

	def __unicode__(self):
		return self.litter

kennel/puppies/views.py
from django.shortcuts import render

from models import Puppies

def puppies(request):
	puppies = Puppies.objects.all()
	return render(request, 'puppies/puppies.html', {'puppies': puppies})

def litter(request, puppies_id):
	litter = Puppies.objects.get(id=puppies_id)
	return render(request, 'puppies/litter.html', {'litter': litter})

puppies/views.py
from django.shortcuts import render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from models import Puppies

def puppies(request):
	puppies = Puppies.objects.all().order_by('-pk')

	paginator = Paginator(puppies, 5)
	page = request.GET.get('page')
	try:
		page_puppies = paginator.page(page)
	except PageNotAnInteger:
		page_puppies = paginator.page(1)
	except EmptyPage:
		page_puppies = paginator.page(paginator.num_page)
	return render(request, 'puppies/puppies.html', {'page_puppies': page_puppies})

def litter(request, puppies_id):
	litter = Puppies.objects.get(id=puppies_id)
	return render(request, 'puppies/litter.html', {'litter': litter})

puppies/templates/puppies/litter.html
{% extends 'base.html' %}
{% load i18n %}
{% block title  %}{% trans 'Litter' %} {{ litter.litter }}{% endblock %}
{% load thumbnail %}
{% block content %}
	<center>
	<h3>{% trans 'Litter' %} {{ litter.litter }}</h3>
	<h5>{% trans 'Birthday'%}: {{ litter.birthday }}</h5>
	<h5>{% trans 'Amount' %}: {{ litter.amount }} </h5>
	
	<h4>{% trans 'Mother'%}: {{ litter.mother }} x {% trans 'Father'%}: {{ litter.father }}</h4>
	</center>
	<table class='table'>
		<tr>
			{% if litter.mother_photo %}
			<td><a href='{{ MEDIA_URL }}{{ litter.mother_photo }}' rel="prettyPhoto[pp_gal]">
				<img src="{{ MEDIA_URL }}{{ litter.mother_photo }}" width=300 height=300></a>
			</td>
			{% endif %}
			{% if litter.father_photo %}
			<td><a href='{{ MEDIA_URL }}{{ litter.father_photo }}' rel="prettyPhoto[pp_gal]">
				<img src="{{ MEDIA_URL }}{{ litter.father_photo }}" width=300 height=300></a>
			</td>
			{% endif %}
		</tr>	
		<tr><td>{% if litter.mother_health %}
				<b>{% trans 'Health' %}:</b> {{ litter.mother_health }}
			{% endif %}</td>
			<td>{% if litter.father_health %}
				<b>{% trans 'Health' %}:</b> {{ litter.father_health }}
			{% endif %} </td>
		</tr>	
		<tr><td>{% if litter.mother_pedigree %}
				<a href={{ litter.mother_pedigree }}>{% trans 'Mother pedigree' %}</a>
			{% endif %}</td>
			<td>{% if litter.father_pedigree %}
				<a href={{ litter.father_pedigree }}>{% trans 'Father pedigree' %}</a>
			{% endif %}</td>
		</tr>
		<tr><td>{% if litter.mother_titles %}
				<b>{% trans 'Entitlements' %}:</b> {{ litter.mother_titles }}
			{% endif %}</td>
			<td>{% if litter.father_titles %}
				<b>{% trans 'Entitlements' %}:</b> {{ litter.father_titles }}
			{% endif %} </td>
		</tr>	
		<tr><td>{% if litter.mother_training %}
				<b>{% trans 'Achievements' %}:</b> {{ litter.mother_training }}
			{% endif %}</td>
			<td>{% if litter.father_training %}
				<b>{% trans 'Achievements' %}:</b> {{ litter.father_training }}
			{% endif %} </td>
		</tr>	
		
	</table>
	{% if litter.gallery.id %}
		<h3><a href="{% url 'gallery:album' litter.gallery.id 'thumbnails' %}">{{ litter.gallery.title }} </a> ({{ litter.gallery.image_set.count }}  {% blocktrans count litter.gallery.image_set.count as counter %}image{% plural %}images{% endblocktrans %})</h3>
		<ul>
		{% for img in litter.gallery.image_set.all %}
			{% thumbnail img '200x200' crop='center' as im %}
			<a href="{{ MEDIA_URL }}{{ img }}" rel="prettyPhoto[pp_gal]"><img src='{{ im.url }}' alt="{{ im.title }}" width="{{ im.width }}" height="{{ im.height }}" class='img-rounded'></a>
			{% endthumbnail %}
		{% endfor %}
		</ul>
	{% endif %}
{% endblock %}

puppies/templates/puppies/puppies.html
{% extends 'base.html' %}
{% load i18n %}
{% block title  %}{% trans 'Our puppies' %}{% endblock %}
{% block content %}
{% for pupp in page_puppies %}
	<center>
	<h3><a href="{% url 'puppies:litter' pupp.id %}">{% trans 'Litter' %} {{ pupp.litter }}</a></3>
	<h2>{% trans 'Mother' %}: {{ pupp.mother }} x {% trans 'Father' %}: {{ pupp.father }}</h2>
	<h5>{% trans 'Birthday' %}: {{ pupp.birthday }}</h5>
	<h5>{% trans 'Amount' %}: {{ pupp.amount }}</h5>
	
	
	{% if pupp.mother_photo %}
	<img src="{{ MEDIA_URL }}{{ pupp.mother_photo }}" width=400 height=400>

	{% endif %}
	{% if pupp.father_photo %}
	<img src="{{ MEDIA_URL }}{{ pupp.father_photo }}" width=400 height=400>
	{% endif %}
	</center>
	<br/>
	<br/>
	<div class='row-fluid'>
		<div class='offset10'><a href="{% url 'puppies:litter' pupp.id %}">{% trans 'More'%}...</a></div>
	</div>
{% endfor %}

 <div class='pagination'>
  <span class="step-links">
    <div class='pagination-current'>
            {% blocktrans with page_puppies.number as page_puppies.number and page_puppies.paginator.num_pages as page_puppies.paginator.num_pages %}Page {{ page_puppies.number }} of {{ page_puppies.paginator.num_pages }}{% endblocktrans %}
    </div>


    {% if page_puppies.has_previous %}
      <a class="pagination-control left" href="?page={{ page_puppies.previous_page_number }}">&lsaquo;</a>
    {% endif %}

      
    {% if page_puppies.has_next %}
      <a class="pagination-control right" href="?page={{ page_puppies.next_page_number }}">&rsaquo;</a>
    {% endif %}
    </span>
</div>
{% endblock %}