dogs/urls.py
from django.conf.urls import patterns, include, url
from views import *

urlpatterns = patterns('',
	url(r'^$', our_dogs, name='our_dogs'),
	url(r'^males/$', males, name='males'),
	url(r'^females/$', females, name='females'),
	url(r'^(?P<dog_id>\d+)/$', dog_page, name='dog_page')

)

gallery/urls.py
from django.conf.urls import url, patterns
from views import albums, album

urlpatterns = patterns('',
	url(r'^albums/$', albums, name='albums'),
	url(r'^(?P<album_id>\d+)/(?P<view>full|thumbnails)/$', album, name='album'),

)

kennel/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()



from django.conf.urls import *
from django.conf import settings

from views import home
from contacts.views import ContactCreateView
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'kennel.views.home', name='home'),
    # url(r'^kennel/', include('kennel.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', home, name='home'),
    #url(r'^gallery/', include('photogallery.urls', namespace='photogallery')),
    url(r'^news/', include('news.urls', namespace='news')),
    url(r'^dogs/', include('dogs.urls', namespace='dogs')),
    url(r'^puppies/', include('puppies.urls', namespace='puppies')),
    url(r'^offsprings/', include('offsprings.urls', namespace='offsprings')),
    url(r'^history/$', TemplateView.as_view(template_name='history.html'), name='history'),
    url(r'^standard/$', TemplateView.as_view(template_name='standard.html'), name='standard'),
    url(r'^whythisbreed/$', TemplateView.as_view(template_name='whythisbreed.html'), name='whythisbreed'),
    url(r'^contacts/$', ContactCreateView.as_view(), name='contacts'),
    url(r'^thanks/$', TemplateView.as_view(template_name='success_contact.html')),
    url(r'^gallery/', include('gallery.urls', namespace='gallery')),
    #url(r'^i18n/', include('django.conf.urls.i18n')),
)


urlpatterns += patterns('',
    
    #(r'^localeurl/', include('localeurl.urls')),\
    (r'^i18n/', include('django.conf.urls.i18n')),
    
)
#for media
urlpatterns += patterns('',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
)

#for captcha 
urlpatterns += patterns('',
    url(r'^captcha/', include('captcha.urls')),
)

offsprings/urls.py
from django.conf.urls import url, patterns

from views import offsprings, offspring_page

urlpatterns = patterns('',
	url(r'^$', offsprings, name ='our_offsprings'),
	url(r'^(?P<offspring_id>\d+)/$', offspring_page, name = 'offspring_page'),

)

offsprings/models.py
from django.db import models

import datetime

from dogs.models import Gender
from gallery.models import Album

class Offspring(models.Model):
	name = models.CharField(max_length=80)
	mother = models.CharField(max_length=80)
	father = models.CharField(max_length=80)
	owner = models.CharField(max_length=80, blank=True)
	city = models.CharField(max_length=80, blank=True)
	photo = models.ImageField(upload_to='media', blank=True)
	sex = models.ForeignKey(Gender)
	birthday = models.DateField()
	pedigree = models.URLField(max_length=150, blank=True)
	hd = models.CharField('HD', max_length = 40, blank=True) 
	mdr1 = models.CharField('MDR1', max_length = 40, blank=True)
	dm = models.CharField('DM', max_length=40, blank=True)
	titles = models.TextField(blank=True)
	training = models.CharField(max_length=80, blank=True)
	about_dog = models.TextField(blank=True)
	gallery = models.ForeignKey(Album)

	def __unicode__(self):
		return self.name

kennel/offsprings/views.py
from django.shortcuts import render

from models import Offspring

def offsprings(request):
	offsprings = Offspring.objects.all()
	return render(request, 'offsprings/offsprings.html', {'offsprings': offsprings})

def offspring_page(request, offspring_id):
	offspring = Offspring.objects.get(id=offspring_id)
	return render(request, 'offsprings/offspring_page.html', {'offspring': offspring})

offsprings/views.py
from django.shortcuts import render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from models import Offspring

def offsprings(request):
	offsprings = Offspring.objects.all()

	paginator = Paginator(offsprings, 5)
	page = request.GET.get('page')
	try:
		page_offsprings = paginator.page(page)
	except PageNotAnInteger:
		page_offsprings = paginator.page(1)
	except EmptyPage:
		page_offsprings = paginator.page(paginator.num_page)
	return render(request, 'offsprings/offsprings.html', {'page_offsprings': page_offsprings})

def offspring_page(request, offspring_id):
	offspring = Offspring.objects.get(id=offspring_id)
	return render(request, 'offsprings/offspring_page.html', {'offspring': offspring})

offsprings/templates/offsprings/offspring_page.html
{% extends 'base.html' %}
{% load i18n %}

{% block title  %}{{  offspring.name }}{% endblock %}
{% load thumbnail %}
{% block content %}
	<center>
	<h3>{{ offspring.name }}</h3>
	<h4>{% trans 'Mother' %}: {{ offspring.mother }} x {% trans 'Father' %}: {{ offspring.father }}</h4>
	<p><b>{% trans 'Birthday' %}:</b> {{ offspring.birthday }} <b>{% trans 'Sex' %}:</b> {{ offspring.sex }}</p>
	{% if offspring.photo %}
	<img src="{{ MEDIA_URL }}{{ offspring.photo }}" width=500 height=500>
	{% endif %}
	</center>
	<p><b>{% trans 'Owner' %}:</b> {{ offspring.owner }}</p>
	<p><b>{% trans 'City' %}:</b> {{ offspring.city }}</p>
	
	
	<p><a href={{ offspring.pedigree }}>{% trans 'Pedigree' %} </a></p>
	<p><b>{% trans 'Health' %}:</b> ED/HD {{ offspring.hd }}, 
	MDR1 {{ offspring.mdr1 }}, 
	DM {{ offspring.dm }}</p>
	<p><b>{% trans 'Entitlements' %}:</b> {{ offspring.titles }}</p>
	<p><b>{% trans 'Achievements' %}:</b> {{ offspring.training }}</p>
	<p><b>{% trans 'About dog' %}:</b> {{ offspring.about_dog }}</p>
	{% if offspring.gallery.id %}
	<h3><a href="{% url 'gallery:album' offspring.gallery.id 'thumbnails' %}">{{ offspring.gallery.title }} </a> ({{ offspring.gallery.image_set.count }} {% blocktrans count offspring.gallery.image_set.count as counter %}image{% plural %}images{% endblocktrans %})</h3>
		<ul>
		{% for img in offspring.gallery.image_set.all %}
			{% thumbnail img '200x200' crop='center' as im %}
			<a href="{{ MEDIA_URL }}{{ img }}" rel="prettyPhoto[pp_gal]"><img src='{{ im.url }}' alt="{{ im.title }}" width="{{ im.width }}" height="{{ im.height }}" class='img-rounded'></a>
			{% endthumbnail %}
		{% endfor %}
		</ul>
	{% endif %}

{% endblock %}

offsprings/templates/offsprings/offsprings.html
{% extends 'base.html' %}

{% load i18n %}

{% block title  %}{% trans 'Our offsprings' %}{% endblock %}

{% block content %}
{% for offspring in page_offsprings %}
	<center>
	<h3><a href="{% url 'offsprings:offspring_page' offspring.id %}">{{ offspring.name }}</a></h3>
	{% if offspring.photo %}
	<img src="{{ MEDIA_URL }}{{ offspring.photo }}" width=500 height=500>
	
	{% endif %}
	
	<h4>{% trans 'Mother' %}: {{ offspring.mother }} x {% trans 'Father' %}: {{ offspring.father }}</h4>
	{% if offspring.owner %}
	<p><b>{% trans 'Owner' %}:</b> {{ offspring.owner }}</p>
	{% endif %}

	{% if offspring.owner %}
	<p><b>{% trans 'City' %}:</b> {{ offspring.city }}</p>
	{% endif %}
	</center>
	<div class='row-fluid'>
		<div class='offset8'><a href="{% url 'offsprings:offspring_page' offspring.id %}">{% trans 'More' %}...</a></div>
	</div>
{% endfor %}

 <div class='pagination'>
  <span class="step-links">
    <div class='pagination-current'>
            {% blocktrans with page_offsprings.number as page_offsprings.number and page_offsprings.paginator.num_pages as page_offsprings.paginator.num_pages %}Page {{ page_offsprings.number }} of {{ page_offsprings.paginator.num_pages }}{% endblocktrans %}
    </div>


    {% if page_offsprings.has_previous %}
      <a class="pagination-control left" href="?page={{ page_offsprings.previous_page_number }}">&lsaquo;</a>
    {% endif %}

      
    {% if page_offsprings.has_next %}
      <a class="pagination-control right" href="?page={{ page_offsprings.next_page_number }}">&rsaquo;</a>
    {% endif %}
    </span>
</div>
{% endblock %}