dogs/urls.py
from django.conf.urls import patterns, include, url
from views import *

urlpatterns = patterns('',
	url(r'^$', our_dogs, name='our_dogs'),
	url(r'^males/$', males, name='males'),
	url(r'^females/$', females, name='females'),
	url(r'^(?P<dog_id>\d+)/$', dog_page, name='dog_page')

)

gallery/urls.py
from django.conf.urls import url, patterns
from views import albums, album

urlpatterns = patterns('',
	url(r'^albums/$', albums, name='albums'),
	url(r'^(?P<album_id>\d+)/(?P<view>full|thumbnails)/$', album, name='album'),

)

kennel/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()



from django.conf.urls import *
from django.conf import settings

from views import home
from contacts.views import ContactCreateView
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'kennel.views.home', name='home'),
    # url(r'^kennel/', include('kennel.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', home, name='home'),
    #url(r'^gallery/', include('photogallery.urls', namespace='photogallery')),
    url(r'^news/', include('news.urls', namespace='news')),
    url(r'^dogs/', include('dogs.urls', namespace='dogs')),
    url(r'^puppies/', include('puppies.urls', namespace='puppies')),
    url(r'^offsprings/', include('offsprings.urls', namespace='offsprings')),
    url(r'^history/$', TemplateView.as_view(template_name='history.html'), name='history'),
    url(r'^standard/$', TemplateView.as_view(template_name='standard.html'), name='standard'),
    url(r'^whythisbreed/$', TemplateView.as_view(template_name='whythisbreed.html'), name='whythisbreed'),
    url(r'^contacts/$', ContactCreateView.as_view(), name='contacts'),
    url(r'^thanks/$', TemplateView.as_view(template_name='success_contact.html')),
    url(r'^gallery/', include('gallery.urls', namespace='gallery')),
    #url(r'^i18n/', include('django.conf.urls.i18n')),
)


urlpatterns += patterns('',
    
    #(r'^localeurl/', include('localeurl.urls')),\
    (r'^i18n/', include('django.conf.urls.i18n')),
    
)
#for media
urlpatterns += patterns('',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
)

#for captcha 
urlpatterns += patterns('',
    url(r'^captcha/', include('captcha.urls')),
)

news/urls.py
from django.conf.urls import url, patterns

from views import news_page

urlpatterns = patterns('',
	url(r'^(?P<news_id>\d+)/$', news_page, name='news_page'),
)

offsprings/urls.py
from django.conf.urls import url, patterns

from views import offsprings, offspring_page

urlpatterns = patterns('',
	url(r'^$', offsprings, name ='our_offsprings'),
	url(r'^(?P<offspring_id>\d+)/$', offspring_page, name = 'offspring_page'),

)

puppies/urls.py
from django.conf.urls import patterns, url
from views import puppies, litter

urlpatterns = patterns('',
	url(r'^$', puppies, name='our_puppies'),
	url(r'^(?P<puppies_id>\d+)/$', litter, name='litter'),
)

contacts/models.py
from django.db import models
from django.forms import ModelForm, Textarea, TextInput
from captcha.fields import CaptchaField
from django.utils.translation import ugettext_lazy as _
#class Contact(models.Model):

class Contact(models.Model):
	title = models.CharField(_('Message title'), max_length=100)
	name = models.CharField(_('Your name'), max_length=100)
	mail = models.EmailField(_('Your email adress'), max_length=100)
	text = models.TextField(_('Message'))

	class Meta:
		verbose_name = 'Message'
		verbose_name_plural = 'Messages'

	def __unicode__(self):
		return self.title

class ContactForm(ModelForm):
	captcha = CaptchaField(label=_('Confirmation code'))

	class Meta:
		model = Contact
		

contacts/views.py
from django.conf import settings
from django.views.generic import CreateView
from django.core.mail import send_mail
#
from contacts.models import Contact, ContactForm

class ContactCreateView(CreateView):
	form_class = ContactForm
	template_name= 'contacts.html'
	success_url = '/thanks/'

	def form_valid(self, form):
		message = '{name} / {mail} write: '.format(
			name=form.cleaned_data.get('name').encode('utf-8'),
			mail=form.cleaned_data.get('mail').encode('utf-8')
		)
		message += '\n\n{0}'.format(form.cleaned_data.get('text').encode('utf-8'))
		send_mail(
			subject=form.cleaned_data.get('title').encode('utf-8').strip(),
			message=message,
			from_email='contact-form@kennel.com',
			recipient_list=settings.LIST_OF_EMAIL_RECIPIENTS
		)
		return super(ContactCreateView, self).form_valid(form)# Create your views here.

templates/album.html
{% load thumbnail %}
<h3><a href="{% url 'gallery:album' album.id 'thumbnails' %}">{{ album.title }} </a> ({{ album.image_set.count }} images)</h3>
	<ul>
		{% for img in album.image_set.all %}
			{% thumbnail img '200x200' crop='center' as im %}
			<a href="{{ MEDIA_URL }}{{ img }}" rel="prettyPhoto[pp_gal]"><img src='{{ im.url }}' alt="{{ im.title }}" width="{{ im.width }}" height="{{ im.height }}" class='img-rounded'></a>
			{% endthumbnail %}
		{% endfor %}
	</ul>

templates/base.html
<!DOCTYPE html>
{% load i18n %}
<html>

{% get_current_language as LANGUAGE_CODE %}
<head><title>{% block title %}{% endblock %}</title>
	
	<link rel='stylesheet' href='{{ STATIC_URL }}css/prettyPhoto.css' type='text/css' media='screen' charset='utf-8' />
	<link rel="stylesheet" href="{{ STATIC_URL }}css/bootstrap.css" type='text/css' >
	<link rel="stylesheet" href="{{ STATIC_URL }}css/bootstrap-responsive.css" type='text/css' >
    

	<script src="{{ STATIC_URL }}js/jquery-2.0.3.js" type='text/javascript' charset="utf-8"></script>
	<script src="{{ STATIC_URL }}js/jquery.prettyPhoto.js" type="text/javascript" charset="utf-8"></script>
	<script src="{{ STATIC_URL }}js/bootstrap.js"></script>
	<style>

		a:link {color: #333333;}
		a:hover {color: #333333;}
		a:active {color: #333333;}
	</style>
</head>
<body>

	<div class="navbar navbar-static-top navbar-inverse">
		<div class='navbar-inner'>
			<div class='container'>
			<a class="brand" href="{% url 'home' %}">Kennel</a>
			<ul class='nav'>
				<li><a href="{% url 'home' %}">{% trans 'Main' %}</a></li>
				<li class='dropdown'>
					<a class="dropdown-toggle" data-toggle="dropdown" href='#'>
						{% trans 'About breed' %} <b class="caret"></b>
					</a>
					<ul class="dropdown-menu">
						<li><a href="{% url 'history' %}">{% trans 'History' %}</a></li>
						<li><a href="{% url 'standard' %}">{% trans 'Standard' %}</a></li>
						<li><a href="{% url 'whythisbreed' %}">{% trans 'Why this breed?' %}</a></li>
					</ul>
				</li>
				
				<li class='dropdown'>
					<a class="dropdown-toggle" data-toggle="dropdown" href="#">{% trans 'Our dogs' %}<b class='caret'></b>
					</a>
					<ul class='dropdown-menu'>
						<li><a href="{% url 'dogs:males' %}">{% trans 'Males' %}</a></li>
						<li><a href="{% url 'dogs:females' %}">{% trans 'Females' %}</a></li>
					</ul>
				</li>
				
				<li><a href="{% url 'puppies:our_puppies' %}">{% trans  'Puppies' %}</a></li>
				<li><a href="{% url 'offsprings:our_offsprings' %}">{% trans  'Offsprings' %}</a></li>
				<li><a href="{% url 'gallery:albums' %}">{% trans 'Gallery' %}</a></li>
				<li><a href="{% url 'contacts' %}">{% trans 'Contacts' %}</a></li>

			</ul>
			</div>	
		</div>
	</div>
	<div class='offset11' style="display: inline-block">			
		<form id='lang_en' action='/i18n/setlang/' method='POST'>
			{% csrf_token %}
    		<input type='hidden' name='language' value='en'/>
    		<a href='#' title='{% trans "English" %}' onclick="document.getElementById('lang_en').submit()">
       			<img src='{{ STATIC_URL }}images/english.jpg' width='20'/>
    		</a>
		</form>
	</div>
	<div style="display: inline-block">			
		<form id='lang_ru' action='/i18n/setlang/' method='POST'>
			{% csrf_token %}
    		<input type='hidden' name='language' value='ru'/>
    		<a href='#' title='{% trans "Russian" %}' onclick="document.getElementById('lang_ru').submit()">
        		<img src='{{ STATIC_URL }}images/russian.jpg' width='20'/>
    		</a>
		</form>
	</div>

	<div class='container'>
	{% block content %}
	{% endblock %}
	{% block text %}
	{% endblock %}
	{% block script %}
	{% endblock %}

	<script type="text/javascript" charset="utf-8">
		$(document).ready(function(){
    		$("a[rel^='prettyPhoto']").prettyPhoto();
		});
	</script>
	</div>
</body>	
</html>

templates/contacts.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans 'Contacts' %}{% endblock %}
{% block content %}
<br/>
<br/>
<br/>


		<td><h4>{% trans 'Owners of the kennel' %}:</h4> {% trans 'First name Last name' %}
		<h5>{% trans 'Adress' %}:</h5> {% trans 'Zip Code, Country, City, Street' %}
		<h5>{% trans 'Telephones' %}:</h5> 
		<p>****-***-**-** {% trans 'Name' %} </p>
		<p>****-***-**-** {% trans 'Name' %} </p>
	
	<br/>
	<br/>
	<br/>
	<div class='form right'>
	<h4>{% trans "You can contact us and we'll surely answer you" %}!</h4>
	
	<form method='POST' action=''>
		{% csrf_token %}
		<div class='form mystyle'>
			{{ form }}
		</div>
		<input class='btn btn-inverse offset4'  type='submit' value='{% trans "Send" %}'>
	</form>
</div>
{% endblock %}

templates/history.html
{% extends 'base.html' %}
{% load i18n %}


{% block title %}{% trans 'History' %}{% endblock %}
{% block content %}

{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load i18n %}
{% load thumbnail %}
{% block title %}{% trans 'Home' %}{% endblock %}
{% block content %}

{% for n in all_news %}
	<h3><a href="{% url 'news:news_page' n.id %}">{{ n.title }}</a></h3>
	<center><a href='{{ MEDIA_URL}}{{n.photo}}' rel="prettyPhoto[pp_gal]"><img src='{{ MEDIA_URL}}{{n.photo}}' width=500 heigth=500 class='img-rounded'></a></center>
	<p>{{ n.body }}</p>
	<p align='right'>{{ n.pub_date }}</p>
{% endfor %}


 <div class='pagination'>
  <span class="step-links">
    <div class='pagination-current'>
            {% blocktrans with all_news.number as all_news.number and all_news.paginator.num_pages as all_news.paginator.num_pages %}Page {{ all_news.number }} of {{ all_news.paginator.num_pages }}{% endblocktrans %}
    </div>


    {% if all_news.has_previous %}
      <a class="pagination-control left" href="?page={{ all_news.previous_page_number }}">&lsaquo;</a>
    {% endif %}

      
    {% if all_news.has_next %}
      <a class="pagination-control right" href="?page={{ all_news.next_page_number }}">&rsaquo;</a>
    {% endif %}
    </span>
</div>


{% endblock %}

templates/standard.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans 'Standard' %}{% endblock %}
{% block content %}

{% endblock %}

templates/success_contact.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans 'Thanks' %}!{% endblock %}

{% block content %}
<h2>{% trans "Thanks for your message! We'll answer soon!" %}</h2>
{% endblock %}

templates/whythisbreed.html
{% extends 'base.html' %}
{% load i18n %}


{% block title %}{% trans 'Why this breed' %}?{% endblock %}
{% block content %}

{% endblock %}